### ISSUE TITLE
[BUG] - Using strategies on Array types runs the strategy on array elements instead of the whole array

### ISSUE THREAD

**Issue by khan-saim** [GameBridgeAI/ts_serialize#125]
**Describe the bug** 
When serializing there is a check for `Array.isArray(value)` which, if true, runs the serialization on the individual elements of the array and returns an array of the serialized objects. This is fine in most cases but if you want a custom strategy to serialize an array into a string for example, the behaviour doesnt work, since now you will get an array of the serialized strings. When using strategies at least, the user should be allowed to define the strategy to run on the whole object no matter if it is an array or not. 

**To Reproduce**
```
// Lets say we have an object with a property that is an array of objects that we want to serialize into one single string
@SerializeProperty({ toJSONStrategy: objArraySerialize, fromJSONStrategy: objArrayDeserialize })
public myProp:{id: number}[];
...

// We expect the strategy will be called with the full array and we can serialize it in one shot. 
const objArraySerialize = (items: {id: number}[]): string {
  return JSON.stringify(items.map(el => el.id));
}

```

In the above what will actually happen is that our `objArraySerialize` will get called for every element in the array instead of the full array.

**Expected behaviour** 
The user should be able to define custom strategies for arrays that use the custom strategy for the entire array rather than just the elements on the array

**Comment by hardy925** [comment]
Thanks, @khan-saim this is a bug for sure and will be a breaking change. Are you interested in providing a PR? If not that is okay.

Thanks again for the report.

**Comment by khan-saim** [comment]
I can take this on, but I will probably only be able to get around to it after a week or so
