### ISSUE TITLE
[BUG] - Doesn't work in Node

### ISSUE THREAD

**Issue by gjuoun** [GameBridgeAI/ts_serialize#150]
**Describe the bug** 

Can't use ts_serialize with Node, error:
```
[ERROR] 16:53:03 TypeError: Class constructor Serializable cannot be invoked without 'new'
```

**To Reproduce** Steps to reproduce the behaviour:
See example code:
```ts
import {
  Serializable,
  SerializeProperty,
  polymorphicClassFromJSON,
} from "@gamebridgeai/ts_serialize";

class MyClass extends Serializable {

  @SerializeProperty({
    serializedKey: "my_string",
  })
  public myProperty = "Hello world!";
}

const myClass = new MyClass();

console.log(JSON.stringify(myClass));

```

**Expected behaviour** 

Print json from a class

**Desktop (please complete the following information):**

- OS: macos
- Node: v14.18.2

**Comment by gjuoun** [comment]
It works well with Deno

**Comment by hardy925** [comment]
can you try with [node 16](https://github.com/GameBridgeAI/ts_serialize/blob/develop/.github/workflows/ts_serialize_release.yml#L65)?

**Comment by gjuoun** [comment]
It doesn't work with node 16 as well.

**Comment by hardy613** [comment]
thanks for the report and code example, we'll investigate.

**Comment by hardy613** [comment]
@ChrisDufourMB Most likely related to our `dtn` additions. Weird that the tests pass from the build

**Comment by ChrisDufourMB** [comment]
I was able to run the provided code in a node project without errors using the given TSConfig options:
Node `v14.19.1` (also tested `v16.15.0`)
```json
{
 "include": ["index.ts"],
    "compilerOptions": {
        "target": "ESNext",
        "moduleResolution":"node",
        "module": "commonjs",
        "experimentalDecorators": true   
 }   
}
```
package.json
```
"@gamebridgeai/ts_serialize": "^2.0.3",
"typescript": "^4.6.4"
```

```sh
/test > tree -L 2
.
├── index.ts
├── node_modules
│   ├── @gamebridgeai
│   └── typescript
├── package-lock.json
├── package.json
└── tsconfig.json

3 directories, 4 files
/test > node node_modules/.bin/tsc -p tsconfig.json
/test > node index.js
"{\"my_string\":\"Hello world!\"}"
```

**Comment by hardy613** [comment]
We should add to our readme what tsconfigs are needed, for example `experimentalDecorators` is required, but not mentioned anywhere

**Comment by hardy613** [comment]
@gjuoun are you able to reproduce the issue if you use the tsconfig settings

```json
{
  "include": ["index.ts"],
  "compilerOptions": {
    "target": "ESNext",
    "moduleResolution":"node",
    "module": "commonjs",
    "experimentalDecorators": true
  }
}
```

**Comment by gjuoun** [comment]
Thanks, the 

> @gjuoun are you able to reproduce the issue if you use the tsconfig settings
> 
> ```json
> {
>   "include": ["index.ts"],
>   "compilerOptions": {
>     "target": "ESNext",
>     "moduleResolution":"node",
>     "module": "commonjs",
>     "experimentalDecorators": true
>   }
> }
> ```

Thanks, the `tsconfig.json` works!

I missed this line 
```ts
    "target": "ESNext",  // was `es5`
```
