### ISSUE TITLE
[RFC] - snake_case and camelCase conversions

### ISSUE THREAD

**Issue by shardyMBAI** [GameBridgeAI/ts_serialize#29]
# Auto snake_case and camelCase conversions

Have a setting or API for setting properties to be auto snake_cased or camelCased.

## Motivation

Time saver without the risk of overriding `content-type`. relates to #7 

## Design Detail

I was thinking of a setting that could be defined in the classes that extend `Serializable`, then if a base class extends and uses the settings to turn on auto-casing then classes that extend the base class would inherit that setting. These classes could optionally turn them off per class or per property with a new `SerializeProperty` option.

**Comment by hardy925** [comment]
I have an idea on the approach, I'll take this one on
