### ISSUE TITLE
[RFC] - JsonNode type

### ISSUE THREAD

**Issue by hardy925** [GameBridgeAI/ts_serialize#59]
# JsonNode type

add a type for `JsonNode` that consists of the correct types supported by the [JSON Notation standard](https://tools.ietf.org/html/rfc8259) 

[text (see "3. Values")](https://tools.ietf.org/rfc/rfc8259.txt)

Note: if updated please follow the `Obsoleted by:` tag in the header: 
<img width="652" alt="Screen Shot 2020-10-16 at 5 42 04 PM" src="https://user-images.githubusercontent.com/27963753/96311208-fc956800-0fd6-11eb-8057-cf98debd6605.png">

## Motivation
To properly type our strategic directions.

`ToJsonStrategy`  and `FromJsonStrategy` make use of `any`, by providing this type we can set up directional strategies.

## Design Detail

The supported RFC types should be `|` (Unioned) into a `JsonNode` type 

```ts
/** Functions used when hydrating data */
export type FromJsonStrategy = (value: any) => any;

/** Functions used when dehydrating data */
export type ToJsonStrategy = (value: any) => any;
```

Becomes

```ts
/** Functions used when hydrating data */
export type FromJsonStrategy<T> = (value: JsonNode) => T;

/** Functions used when dehydrating data */
export type ToJsonStrategy <T>= (value: T) => JsonNode;
```

**Comment by ms1111** [comment]
This is how the lead architect of TypeScript suggests defining it with a recursive type reference, supported in TS 3.7+: https://github.com/microsoft/TypeScript/pull/33050
```ts
type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
```

TS 3.7 was released in Nov 2019.

Here is another solution he posted a few years back for earlier TS versions:

https://github.com/Microsoft/TypeScript/issues/3496#issuecomment-128553540

```ts
type JSONValue = string | number | boolean | JSONObject | JSONArray;

interface JSONObject {
    [x: string]: JSONValue;
}

interface JSONArray extends Array<JSONValue> { }
```

**Comment by hardy613** [comment]
Hello @ms1111 :wave: 

Thanks for looking into this (I had no idea TBH)

```ts
type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
```
Is more along the lines of what I was thinking. Which now I am wondering about the `object` (`{}`) definition if we should use `Record` instead? 


```ts
type Json = string | number | boolean | null | Json[] | Record<string, Json>;
```

**Comment by ms1111** [comment]
> Which now I am wondering about the object ({}) definition if we should use Record instead?
```ts
type Json = string | number | boolean | null | Json[] | Record<string, Json>;
```

`Type alias 'Json' circularly references itself.ts(2456)`

For some reason the `Record` throws it off in a way that `{ [key: string]: Json }` doesn't.

What would you think about this:
```ts
export type JsonObject = { [key: string]: JsonValue };
export type JsonValue = null | boolean | number | string | JsonValue[] | JsonObject;

/** Functions used when hydrating data */
export type FromJsonStrategy<T> = (value: JsonObject) => T;

/** Functions used when dehydrating data */
export type ToJsonStrategy <T>= (value: T) => JsonObject;
```
... explicitly specifying the return type of ToJsonStrategy as JsonObject (an object) rather than just any JSON value. I think that's how it's always used, right? The top-level thing you serialize with ts_serialize has to be an object, not an array or a scalar?

**Comment by hardy925** [comment]
>  I think that's how it's always used, right? The top-level thing you serialize with ts_serialize has to be an object, not an array or a scalar?

Yea, the expected usage is for authors to define how an object is serialized to JSON - this does make sense to me.

Thanks!

**Comment by hardy613** [comment]
actually, sorry, this is my mistake,

in this use case, we can expect an array or scalar value because we are not serializing the top level object here, this would be the description of how a specific property is serialized. 

> The top-level thing you serialize with ts_serialize has to be an object

is correct, however, at this point, we are describing the properties of said object.

**Comment by hardy613** [comment]
```
/** Functions used when hydrating data */
export type FromJsonStrategy<T> = (value: JsonObject | JsonValue) => T;

/** Functions used when dehydrating data */
export type ToJsonStrategy <T>= (value: T) => JsonObject | JsonValue;
```

we still need to manage full JsonObjects though because they can also be a value of the property
