### ISSUE TITLE
[RFC] - Easier Angular HttpClient serialization

### ISSUE THREAD

**Issue by ms1111** [GameBridgeAI/ts_serialize#63]
# Easier Angular HttpClient serialization

Expose toPojo() in Serializable or make toJson() return a JsonObject (related to #59).

## Motivation

In Angular, if you do something like:
```ts
return this.httpClient.post(this.url, mySerializableObject.toJson());
```
... it tries to send the JSON string as `Content-type: text/plain` instead of `application/json`.

## Design Detail
Add a method to the Serializable class expose the internal serialized representation (the POJO before `JSON.stringify()`). In Angular you could then do:
```ts
return this.httpClient.post(this.url, mySerializableObject.toPojo());
```

## Drawbacks
- more noise/confusion in the API

## Rationale and Alternatives
Alternatives:
1. Some kind of HttpClient intereptor to detect a Serializable object and set the character set appropriately. The caller would then do:
```ts
return this.httpClient.post(this.url, mySerializableObject); // some magic will call toJson() on the object
```

2. Or, callers could set HttpClient options to force the right content type on each post/put call.
```ts
const httpOptions = {
    headers: new HttpHeaders({
        'Content-Type': 'application/json',
    })
};
return this.httpClient.post(this.url, mySerializableObject.toJson(), httpOptions);
```

**Comment by hardy925** [comment]
Personally, I am leaning more on this being an angular issue. HttpClient tries to infer the content-type base on the type of. the second value. I like that there are options to solve this outside of the project but I a unsure of the best approach

**Comment by ms1111** [comment]
I think Scott had the idea of exposing a `Serializable.tsSerialize()` method that would return the object in JsonObject form that Angular or other frameworks could use.

(i.e. rename toPojo() to tsSerialize() and make it public)

**Comment by hardy925** [comment]
it was your idea!
