### ISSUE TITLE
[BUG] - Handle deserialization of arrays of nested objects

### ISSUE THREAD

**Issue by ms1111** [GameBridgeAI/ts_serialize#64]
# Handle deserialization of arrays of nested objects

Allow something like fromJsonAs() for arrays of nested objects. Related to #62, but for deserialization. For example:

```ts
class Nested extends Serializable {
    @SerializeProperty("a_property")
    test = true;
}

class Outer extends Serializable {
    @SerializeProperty({ fromJsonStrategy: fromJsonAs(Nested) })
    outer: Nested[] = [Nested(), Nested()];
}
```

Currently this fails:
```ts
test({
  name: "fromJsonAs works with arrays of objects",
  fn() {
    class Test extends Serializable {
      @SerializeProperty("a_property")
      test = true;
    }
    const testObj = new Test();
    const array: Test[] = fromJsonAs(Test)([{ a_property: "v1" }, { a_property: "v2" }]);
    assertEquals(array.length, 2);
    assert(array[0] instanceof Test);
  },
});
```
```
failures:

fromJsonAs works with arrays of objects
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   undefined
+   2
```

## Motivation
Make it easier to handle arrays of nested objects.

## Design Detail
Make fromJsonAs() handle arrays by checking if the input is an array before it tries to build a new object.

## Drawbacks
- ...

## Rationale and Alternatives
Alternative: add a separate fromJsonAsArray() that callers can use instead of fromJsonAs(), something like this:

```ts
export function fromJsonAsArray<T>(type: T & { new (): Serializable }): FromJsonStrategy {
      return (value: any) => (value ? value.map((element: any) => new type().fromJson(element)) : null);
}
```

But I'm not sure the separate function adds any value. It's just one more thing callers would have to remember to do.

**Comment by hardy925** [comment]
we can def look into the test failures, thanks for the report!
