### ISSUE TITLE
[RFC] - polymorphic classes

### ISSUE THREAD

**Issue by hardy925** [GameBridgeAI/ts_serialize#80]
we'll need a way to manage classes with a polymorphic design, I do not have a test for this yet

**Comment by ms1111** [comment]
Here's a thought:
```
    @SerializableProperty({ polymorphicStrategy = classFromType })
    private foo: SomeParentClass;
// ...

// Each base class would need its own associated classFromType() method
function classFromType(input: Object): Object {
    switch (input?._type) {
        case "SomeType1": return new SomeType1();
        case "SomeType2": return new SomeType2();
    }
    throw new Error(...);
}
```
then when we need to create an instance in ts_serialize, if `polymorphicStrategy` is set, we call it to get the new object instead of `new SomeParentClass()`.

**Comment by ms1111** [comment]
Do we need something to handle inserting `_type` into the serialized output, or is that property already going to exist as a real property on the user's class?

**Comment by ChrisDufourMB** [comment]
I think Mike's approach is good, we can make it somewhat implementation independent by making a new abstract class that extends `Serializable`, maybe something like this:

```ts
abstract class PolymorphicSerializable extends Serializable {
  public abstract resolveClass(input: JsonValue | Object): PolymorphicSerializable;
}
```

An implementation may look something like this:
```ts
abstract class MyBaseClass extends PolymorphicSerializable {
  public resolveClass(input: JsonValue | Object): PolymorphicSerializable {
    switch (input["_type"]) {
      case "poly": return new MyPolyClass();    
      case "otherPoly": return new MyOtherPolyClass();    
      default: throw new Error("can't determine poly class")
    }
  }
}

class MyPolyClass extends MyBaseClass {}
class MyOtherPolyClass extends MyBaseClass {}
```

The downside to this is that we may need to serialize the input twice to get this to work and, as you said, it may be up to the developer to make sure that the class differentiator is actually part of all the child classes. This may be made easier by using static properties, or an interface that provides a function and is used to get a serialization value.
