### ISSUE TITLE
[BUG] - error constant missing from NPM package

### ISSUE THREAD

**Issue by ms1111** [GameBridgeAI/ts_serialize#96]
**Describe the bug**
I don't understand how it would happen, but `ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS` is missing from the compiled/babelified ts_serialize.js in the npm package (1.1.0). Other error constants, like `ERROR_TO_OBJECT_CONTAINING_INVALID_VALUE`, are present. But this one is missing.

This shows up when you try to deserialize something with a missing or unknown `@PolymorphicSwitch` value:

```ts
        it("should fail", () => {
            polymorphicClassFromJSON(MyPolymorphicBaseClass, { _type: "flerp" });
        });
```

```
        ReferenceError: ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS is not defined
            at resolvePolymorphicClass (webpack:///./node_modules/@gamebridgeai/ts_serialize/ts_serialize.js?:518:19)
            at Object.polymorphicClassFromJSON2 [as polymorphicClassFromJSON] (webpack:///./node_modules/@gamebridgeai/ts_serialize/ts_serialize.js?:522:10)
...
```

Opening ts_serialize.js, I can see there is no `var ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS` defined.

**Comment by hardy925** [comment]
hmm, would you be able to provide a test in this repo? 

I tried in the `examples/node` tests with `polymorphicClassFromJSON(AbstractClass, { _type: "flerp" });` as a test then running `.github/workflows/scripts/build.sh "v0.0.0"` from the root.

<img width="853" alt="Screen Shot 2020-12-30 at 10 48 53 PM" src="https://user-images.githubusercontent.com/27963753/103393597-7080e000-4af1-11eb-9c13-be35bebce455.png">

Which is what I would expect from our tests.

**Comment by ms1111** [comment]
If you go to a fresh directory and `npm install @gamebridgeai/ts_serialize`, and then open `node_modules/@gamebridgeai/ts_serialize/ts_serialize.js`, there are two instances of `throw new Error(ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS)`, but no declaration of `var ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS = ...`.

Lines 132-136 have the other error constants:
```js
var ERROR_MISSING_PROPERTIES_MAP = "Unable to load serializer properties for the given context";
var ERROR_MISSING_STATIC_OR_VALUE_ON_POLYMORPHIC_SWITCH = "Missing static property value or value in PolymorphicSwitch";
var ERROR_INVALID_DATE = "Invalid Date";
var ERROR_TO_OBJECT_CONTAINING_INVALID_VALUE = "The value is not an object";
var ERROR_TO_OBJECT_CONTAINING_INVALID_SUB_VALUE = "The sub-value is not an object";
```

Not sure why this one's missing in the build output.

**Comment by hardy925** [comment]
okay, I see that now, thanks.

**Comment by hardy925** [comment]
2 reports of this now, need to bump it up

**Comment by ChrisDufourMB** [comment]
Confirmed that when compiled with deno `v1.6.0` `ERROR_FAILED_TO_RESOLVE_POLYMORPHIC_CLASS` is NOT defined in the JS build

When compiled with deno `v1.6.3` it was included, so simply bumping the version should resolve the issue

**Comment by hardy925** [comment]
resolving now
